// <auto-generated />
using InventoryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("InventoryAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Product 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Product 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Product 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Product 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Product 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Product 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Product 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Product 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Product 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Product 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Product 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Product 16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Product 17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Product 18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Product 19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Product 20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Product 21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Product 22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Product 23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Product 24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Product 25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Product 26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Product 27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Product 28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Product 29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Product 30"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Product 31"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Product 32"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Product 33"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Product 34"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Product 35"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Product 36"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Product 37"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Product 38"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Product 39"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Product 40"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Product 41"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Product 42"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Product 43"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Product 44"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Product 45"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Product 46"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Product 47"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Product 48"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Product 49"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Product 50"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Product 51"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Product 52"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Product 53"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Product 54"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Product 55"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Product 56"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Product 57"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Product 58"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Product 59"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Product 60"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Product 61"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Product 62"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Product 63"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Product 64"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Product 65"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Product 66"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Product 67"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Product 68"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Product 69"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Product 70"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Product 71"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Product 72"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Product 73"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Product 74"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Product 75"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Product 76"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Product 77"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Product 78"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Product 79"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Product 80"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Product 81"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Product 82"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Product 83"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Product 84"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Product 85"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Product 86"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Product 87"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Product 88"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Product 89"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Product 90"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Product 91"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Product 92"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Product 93"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Product 94"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Product 95"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Product 96"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Product 97"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Product 98"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Product 99"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Product 100"
                        });
                });

            modelBuilder.Entity("InventoryAPI.Models.StockRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ProductId", "WarehouseId")
                        .IsUnique();

                    b.ToTable("StockRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 10,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            Quantity = 20,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 2,
                            Quantity = 20,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 2,
                            Quantity = 40,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 3,
                            Quantity = 30,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 3,
                            Quantity = 60,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 4,
                            Quantity = 40,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 4,
                            Quantity = 80,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 5,
                            Quantity = 50,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 5,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 6,
                            Quantity = 60,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 6,
                            Quantity = 20,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 7,
                            Quantity = 70,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 7,
                            Quantity = 40,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 8,
                            Quantity = 80,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 8,
                            Quantity = 60,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 9,
                            Quantity = 90,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 9,
                            Quantity = 80,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 10,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 10,
                            Quantity = 10,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 11,
                            Quantity = 10,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 11,
                            Quantity = 20,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 12,
                            Quantity = 20,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 12,
                            Quantity = 40,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 13,
                            Quantity = 30,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 13,
                            Quantity = 60,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 14,
                            Quantity = 40,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 14,
                            Quantity = 80,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 15,
                            Quantity = 50,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 15,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 16,
                            Quantity = 60,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 16,
                            Quantity = 20,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 17,
                            Quantity = 70,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 17,
                            Quantity = 40,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 18,
                            Quantity = 80,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 18,
                            Quantity = 60,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 19,
                            Quantity = 90,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 38,
                            ProductId = 19,
                            Quantity = 80,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 39,
                            ProductId = 20,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 40,
                            ProductId = 20,
                            Quantity = 10,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 41,
                            ProductId = 21,
                            Quantity = 10,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 42,
                            ProductId = 21,
                            Quantity = 20,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 43,
                            ProductId = 22,
                            Quantity = 20,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 44,
                            ProductId = 22,
                            Quantity = 40,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 45,
                            ProductId = 23,
                            Quantity = 30,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 46,
                            ProductId = 23,
                            Quantity = 60,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 47,
                            ProductId = 24,
                            Quantity = 40,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 48,
                            ProductId = 24,
                            Quantity = 80,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 49,
                            ProductId = 25,
                            Quantity = 50,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 50,
                            ProductId = 25,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 51,
                            ProductId = 26,
                            Quantity = 60,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 52,
                            ProductId = 26,
                            Quantity = 20,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 53,
                            ProductId = 27,
                            Quantity = 70,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 54,
                            ProductId = 27,
                            Quantity = 40,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 55,
                            ProductId = 28,
                            Quantity = 80,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 56,
                            ProductId = 28,
                            Quantity = 60,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 57,
                            ProductId = 29,
                            Quantity = 90,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 58,
                            ProductId = 29,
                            Quantity = 80,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 59,
                            ProductId = 30,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 60,
                            ProductId = 30,
                            Quantity = 10,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 61,
                            ProductId = 31,
                            Quantity = 10,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 62,
                            ProductId = 31,
                            Quantity = 20,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 63,
                            ProductId = 32,
                            Quantity = 20,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 64,
                            ProductId = 32,
                            Quantity = 40,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 65,
                            ProductId = 33,
                            Quantity = 30,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 66,
                            ProductId = 33,
                            Quantity = 60,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 67,
                            ProductId = 34,
                            Quantity = 40,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 68,
                            ProductId = 34,
                            Quantity = 80,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 69,
                            ProductId = 35,
                            Quantity = 50,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 70,
                            ProductId = 35,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 71,
                            ProductId = 36,
                            Quantity = 60,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 72,
                            ProductId = 36,
                            Quantity = 20,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 73,
                            ProductId = 37,
                            Quantity = 70,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 74,
                            ProductId = 37,
                            Quantity = 40,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 75,
                            ProductId = 38,
                            Quantity = 80,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 76,
                            ProductId = 38,
                            Quantity = 60,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 77,
                            ProductId = 39,
                            Quantity = 90,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 78,
                            ProductId = 39,
                            Quantity = 80,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 79,
                            ProductId = 40,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 80,
                            ProductId = 40,
                            Quantity = 10,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 81,
                            ProductId = 41,
                            Quantity = 10,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 82,
                            ProductId = 41,
                            Quantity = 20,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 83,
                            ProductId = 42,
                            Quantity = 20,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 84,
                            ProductId = 42,
                            Quantity = 40,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 85,
                            ProductId = 43,
                            Quantity = 30,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 86,
                            ProductId = 43,
                            Quantity = 60,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 87,
                            ProductId = 44,
                            Quantity = 40,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 88,
                            ProductId = 44,
                            Quantity = 80,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 89,
                            ProductId = 45,
                            Quantity = 50,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 90,
                            ProductId = 45,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 91,
                            ProductId = 46,
                            Quantity = 60,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 92,
                            ProductId = 46,
                            Quantity = 20,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 93,
                            ProductId = 47,
                            Quantity = 70,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 94,
                            ProductId = 47,
                            Quantity = 40,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 95,
                            ProductId = 48,
                            Quantity = 80,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 96,
                            ProductId = 48,
                            Quantity = 60,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 97,
                            ProductId = 49,
                            Quantity = 90,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 98,
                            ProductId = 49,
                            Quantity = 80,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 99,
                            ProductId = 50,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 100,
                            ProductId = 50,
                            Quantity = 10,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 101,
                            ProductId = 51,
                            Quantity = 10,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 102,
                            ProductId = 51,
                            Quantity = 20,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 103,
                            ProductId = 52,
                            Quantity = 20,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 104,
                            ProductId = 52,
                            Quantity = 40,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 105,
                            ProductId = 53,
                            Quantity = 30,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 106,
                            ProductId = 53,
                            Quantity = 60,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 107,
                            ProductId = 54,
                            Quantity = 40,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 108,
                            ProductId = 54,
                            Quantity = 80,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 109,
                            ProductId = 55,
                            Quantity = 50,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 110,
                            ProductId = 55,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 111,
                            ProductId = 56,
                            Quantity = 60,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 112,
                            ProductId = 56,
                            Quantity = 20,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 113,
                            ProductId = 57,
                            Quantity = 70,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 114,
                            ProductId = 57,
                            Quantity = 40,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 115,
                            ProductId = 58,
                            Quantity = 80,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 116,
                            ProductId = 58,
                            Quantity = 60,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 117,
                            ProductId = 59,
                            Quantity = 90,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 118,
                            ProductId = 59,
                            Quantity = 80,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 119,
                            ProductId = 60,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 120,
                            ProductId = 60,
                            Quantity = 10,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 121,
                            ProductId = 61,
                            Quantity = 10,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 122,
                            ProductId = 61,
                            Quantity = 20,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 123,
                            ProductId = 62,
                            Quantity = 20,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 124,
                            ProductId = 62,
                            Quantity = 40,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 125,
                            ProductId = 63,
                            Quantity = 30,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 126,
                            ProductId = 63,
                            Quantity = 60,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 127,
                            ProductId = 64,
                            Quantity = 40,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 128,
                            ProductId = 64,
                            Quantity = 80,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 129,
                            ProductId = 65,
                            Quantity = 50,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 130,
                            ProductId = 65,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 131,
                            ProductId = 66,
                            Quantity = 60,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 132,
                            ProductId = 66,
                            Quantity = 20,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 133,
                            ProductId = 67,
                            Quantity = 70,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 134,
                            ProductId = 67,
                            Quantity = 40,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 135,
                            ProductId = 68,
                            Quantity = 80,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 136,
                            ProductId = 68,
                            Quantity = 60,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 137,
                            ProductId = 69,
                            Quantity = 90,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 138,
                            ProductId = 69,
                            Quantity = 80,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 139,
                            ProductId = 70,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 140,
                            ProductId = 70,
                            Quantity = 10,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 141,
                            ProductId = 71,
                            Quantity = 10,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 142,
                            ProductId = 71,
                            Quantity = 20,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 143,
                            ProductId = 72,
                            Quantity = 20,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 144,
                            ProductId = 72,
                            Quantity = 40,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 145,
                            ProductId = 73,
                            Quantity = 30,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 146,
                            ProductId = 73,
                            Quantity = 60,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 147,
                            ProductId = 74,
                            Quantity = 40,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 148,
                            ProductId = 74,
                            Quantity = 80,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 149,
                            ProductId = 75,
                            Quantity = 50,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 150,
                            ProductId = 75,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 151,
                            ProductId = 76,
                            Quantity = 60,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 152,
                            ProductId = 76,
                            Quantity = 20,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 153,
                            ProductId = 77,
                            Quantity = 70,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 154,
                            ProductId = 77,
                            Quantity = 40,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 155,
                            ProductId = 78,
                            Quantity = 80,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 156,
                            ProductId = 78,
                            Quantity = 60,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 157,
                            ProductId = 79,
                            Quantity = 90,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 158,
                            ProductId = 79,
                            Quantity = 80,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 159,
                            ProductId = 80,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 160,
                            ProductId = 80,
                            Quantity = 10,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 161,
                            ProductId = 81,
                            Quantity = 10,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 162,
                            ProductId = 81,
                            Quantity = 20,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 163,
                            ProductId = 82,
                            Quantity = 20,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 164,
                            ProductId = 82,
                            Quantity = 40,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 165,
                            ProductId = 83,
                            Quantity = 30,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 166,
                            ProductId = 83,
                            Quantity = 60,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 167,
                            ProductId = 84,
                            Quantity = 40,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 168,
                            ProductId = 84,
                            Quantity = 80,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 169,
                            ProductId = 85,
                            Quantity = 50,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 170,
                            ProductId = 85,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 171,
                            ProductId = 86,
                            Quantity = 60,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 172,
                            ProductId = 86,
                            Quantity = 20,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 173,
                            ProductId = 87,
                            Quantity = 70,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 174,
                            ProductId = 87,
                            Quantity = 40,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 175,
                            ProductId = 88,
                            Quantity = 80,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 176,
                            ProductId = 88,
                            Quantity = 60,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 177,
                            ProductId = 89,
                            Quantity = 90,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 178,
                            ProductId = 89,
                            Quantity = 80,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 179,
                            ProductId = 90,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 180,
                            ProductId = 90,
                            Quantity = 10,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 181,
                            ProductId = 91,
                            Quantity = 10,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 182,
                            ProductId = 91,
                            Quantity = 20,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 183,
                            ProductId = 92,
                            Quantity = 20,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 184,
                            ProductId = 92,
                            Quantity = 40,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 185,
                            ProductId = 93,
                            Quantity = 30,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 186,
                            ProductId = 93,
                            Quantity = 60,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 187,
                            ProductId = 94,
                            Quantity = 40,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 188,
                            ProductId = 94,
                            Quantity = 80,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 189,
                            ProductId = 95,
                            Quantity = 50,
                            WarehouseId = 6
                        },
                        new
                        {
                            Id = 190,
                            ProductId = 95,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 191,
                            ProductId = 96,
                            Quantity = 60,
                            WarehouseId = 7
                        },
                        new
                        {
                            Id = 192,
                            ProductId = 96,
                            Quantity = 20,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 193,
                            ProductId = 97,
                            Quantity = 70,
                            WarehouseId = 8
                        },
                        new
                        {
                            Id = 194,
                            ProductId = 97,
                            Quantity = 40,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 195,
                            ProductId = 98,
                            Quantity = 80,
                            WarehouseId = 9
                        },
                        new
                        {
                            Id = 196,
                            ProductId = 98,
                            Quantity = 60,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 197,
                            ProductId = 99,
                            Quantity = 90,
                            WarehouseId = 10
                        },
                        new
                        {
                            Id = 198,
                            ProductId = 99,
                            Quantity = 80,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 199,
                            ProductId = 100,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 200,
                            ProductId = 100,
                            Quantity = 10,
                            WarehouseId = 6
                        });
                });

            modelBuilder.Entity("InventoryAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InventoryAPI.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Warehouse 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Warehouse 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Warehouse 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Warehouse 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Warehouse 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Warehouse 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Warehouse 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Warehouse 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Warehouse 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Warehouse 10"
                        });
                });

            modelBuilder.Entity("InventoryAPI.Models.StockRecord", b =>
                {
                    b.HasOne("InventoryAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryAPI.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });
#pragma warning restore 612, 618
        }
    }
}
